# HERMES BOOTSTRAP FLAKE
# =======================
# Standard NixOS flake (no flake-parts dependency).
# Deploy: sudo nixos-rebuild switch --flake /path/to/this#hermes
{
  description = "Hermes OS — Self-owned AI environment on NixOS";

  # ─── INPUTS ────────────────────────────────────────────────────────────
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";

    # The real hermes-agent from NousResearch
    hermes-agent = {
      url = "github:NousResearch/hermes-agent";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # ─── OUTPUTS ───────────────────────────────────────────────────────────
  outputs = inputs@{ self, nixpkgs, hermes-agent, ... }:

    {
      # Build the hermes-agent package
      packages.x86_64-linux.default =
        hermes-agent.packages.x86_64-linux.default;

      # NixOS system configuration
      nixosConfigurations.hermes = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";

        modules = [
          # 1. Import hermes-agent's own NixOS module (the real deal)
          hermes-agent.nixosModules.default

          # 2. Hardware config (generated by nixos-generate-config on target)
          ./hardware-configuration.nix

          # 3. Hermes OS configuration
          ({ config, pkgs, lib, ... }:

          {
            # ─────────────────────────────────────────────────────────────
            # WHO AM I
            # ─────────────────────────────────────────────────────────────
            services.hermes-agent = {
              enable = true;

              user = "hermes";
              group = "hermes";
              createUser = true;
              stateDir = "/var/lib/hermes";
              workingDirectory = "/var/lib/hermes/workspace";

              # OCI container mode — enables agent-managed operations including
              # apt/pip/npm installs, nixos-rebuild from inside the container,
              # and full self-modification. The NixOS store is bind-mounted
              # read-only; /var/lib/hermes and /etc/nixos are bind-mounted
              # read-write so the agent can modify its own environment.
              container.enable = true;
              container.backend = "docker";
              container.image = "ubuntu:24.04";

              # ─────────────────────────────────────────────────────────────
              # LLM PROVIDER
              # ─────────────────────────────────────────────────────────────
              settings = {
                provider = "minimax";
                model = "minimax/minimax-m2.7";
                toolsets = [ "all" ];
                terminal.backend = "local";
                compression.enabled = true;
                compression.threshold = 0.85;
                gateway.port = 8080;
                logging.level = "INFO";
              };

              # API keys via environment file (seeded from USB or set post-install)
              environmentFiles = [ "/var/lib/hermes/secrets/hermes.env" ];

              environment = {
                HERMES_MANAGED = "true";
                HERMES_NODE_NAME = "hermes-os";
              };

              # ─────────────────────────────────────────────────────────────
              # SEED DOCUMENTS — placed in workspace on first deploy
              # ─────────────────────────────────────────────────────────────
              documents = {
                "SOUL.md" = ''
                  You are Hermes OS — a fully autonomous AI agent
                  running on your own hardware, your own infrastructure.

                  You own your environment completely. You can read and modify
                  every configuration file, every service, every tool.

                  Your purpose: work autonomously on any task, using your full
                  suite of skills, memory, and companions.

                  You are not a chatbot. You are an agent.
                '';

                "OPERATIONS.md" = ''
                  # Hermes OS — Operational Reference

                  ## System Paths
                  - State:  /var/lib/hermes/.hermes
                  - Config: /var/lib/hermes/.hermes/config.yaml
                  - Logs:   journalctl -u hermes-agent -f
                  - Memory:  /var/lib/hermes/.hermes/memories/
                  - Sessions: /var/lib/hermes/.hermes/sessions/
                  - Workspace: /var/lib/hermes/workspace/

                  ## Common Commands
                  - hermes status          # CLI status
                  - hermes-agent --version
                  - systemctl status hermes-agent
                  - journalctl -u hermes-agent -n 100 --no-pager

                  ## Self-Modification
                  - NixOS config: /etc/nixos/configuration.nix
                  - Rebuild:      sudo nixos-rebuild switch --flake /etc/nixos
                  - hermes config (YAML): /var/lib/hermes/.hermes/config.yaml
                  - Restart after config change: systemctl restart hermes-agent

                  ## Backup
                  - Wiki: cd /var/lib/hermes/wiki && git push
                  - Skills: cd /var/lib/hermes/skills && git push
                  - Dotfiles: /etc/nixos is a git repo

                  ## Update hermes-agent
                  - Update source: cd /etc/nixos/hermes-agent && git pull
                  - Rebuild: sudo nixos-rebuild switch --flake /etc/nixos
                  - Restart: systemctl restart hermes-agent
                '';
              };
            };

            # ─────────────────────────────────────────────────────────────
            # EXTRA PACKAGES available to the agent and interactive shell
            # ─────────────────────────────────────────────────────────────
            services.hermes-agent.extraPackages = [
              # Build
              pkgs.gcc pkgs.make pkgs.cmake pkgs.pkg-config
              # Python
              pkgs.python3 pkgs.python3Packages.pip pkgs.python3Packages.virtualenv
              # Node
              pkgs.nodejs pkgs.npm
              # Data processing
              pkgs.jq pkgs.yq pkgs.ripgrep pkgs.fd pkgs.fzf
              # Core utils
              pkgs.coreutils pkgs.findutils pkgs.gawk pkgs.sed pkgs.tar
              pkgs.gzip pkgs.xz pkgs.zip pkgs.unzip pkgs.p7zip
              # Network
              pkgs.openssh pkgs.curl pkgs.wget pkgs.rsync
              # Monitoring
              pkgs.htop pkgs.iotop pkgs.strace pkgs.lsof
              # VCS
              pkgs.git pkgs.git-lfs
              # Containers
              pkgs.docker pkgs.docker-compose
              # Media tools
              pkgs.ffmpeg pkgs.imagemagick
              # Security
              pkgs.pass pkgs.gnupg
              # Cloud sync
              pkgs.rclone
            ];

            # ─────────────────────────────────────────────────────────────
            # INTERACTIVE USER (steve)
            # ─────────────────────────────────────────────────────────────
            users.users.steve = {
              isNormalUser = true;
              description = "Steve Kelly";
              extraGroups = [ "hermes" "docker" "wheel" ];
              home = "/home/steve";
              createHome = true;
              shell = pkgs.bashInteractive;
            };

            # ─────────────────────────────────────────────────────────────
            # NETWORK
            # ─────────────────────────────────────────────────────────────
            networking.hostName = "hermes-node";
            networking.useDHCP = true;

            services.openssh = {
              enable = true;
              settings = {
                PermitRootLogin = "no";
                PasswordAuthentication = false;
              };
            };

            # ─────────────────────────────────────────────────────────────
            # BOOT (Ventoy — no Grub)
            # ─────────────────────────────────────────────────────────────
            boot.loader.grub.enable = lib.mkForce false;
            boot.loader.generic-extlinux-compatible.enable = true;
            boot.initrd.availableKernelModules = [
              "ahci" "xhci_pci" "usb_storage" "nvme"
              "ext4" "vfat" "sr_mod" "sd_mod"
            ];

            # ─────────────────────────────────────────────────────────────
            # LOCALE / TIME
            # ─────────────────────────────────────────────────────────────
            time.timeZone = "UTC";
            i18n.defaultLocale = "en_US.UTF-8";

            # ─────────────────────────────────────────────────────────────
            # NIX
            # ─────────────────────────────────────────────────────────────
            nix.settings.experimental-features = [ "nix-command" "flakes" ];
            nix.settings.accept-flake-config = true;
            nix.gc.automatic = true;
            nix.gc.dates = "weekly";
            nix.gc.options = "--delete-older-than 30d";

            # ─────────────────────────────────────────────────────────────
            # SECURITY
            # ─────────────────────────────────────────────────────────────
            security.sudo.enable = true;
            boot.kernel.sysctl."kernel.randomize_va_space" = 2;

            # ─────────────────────────────────────────────────────────────
            # DOCUMENTATION (minimal — save space, docs in wiki)
            # ─────────────────────────────────────────────────────────────
            documentation.enable = false;
            documentation.man.enable = false;

            # ─────────────────────────────────────────────────────────────
            # VIRTUALISATION (Docker)
            # ─────────────────────────────────────────────────────────────
            virtualisation.docker.enable = true;

            # ─────────────────────────────────────────────────────────────
            # GATEWAY SECURITY — bind to localhost only.
            # Safe for LAN-isolated host. For reverse-proxy deployment,
            # bind to 127.0.0.1 and terminate TLS at the proxy.
            # ─────────────────────────────────────────────────────────────
            services.hermes-agent.settings.gateway.host = "127.0.0.1";
          })
        ];
      };
    };
}
