# HERMES BOOTSTRAP FLAKE
# =======================
# Standard NixOS flake (no flake-parts dependency).
# Deploy: sudo nixos-rebuild switch --flake /path/to/this#hermes
{
  description = "Hermes OS — Self-owned AI environment on NixOS";

  # ─── INPUTS ────────────────────────────────────────────────────────────
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";

    # The real hermes-agent from NousResearch
    hermes-agent = {
      url = "github:NousResearch/hermes-agent";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # ─── OUTPUTS ───────────────────────────────────────────────────────────
  outputs = inputs@{ self, nixpkgs, hermes-agent, ... }:
    let
      deployment = import ./deployment-options.nix;
    in
    {
      # Build the hermes-agent package
      packages.x86_64-linux.default =
        hermes-agent.packages.x86_64-linux.default;

      # NixOS system configuration
      nixosConfigurations.hermes = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";

        modules = [
          # 1. Import hermes-agent's own NixOS module (the real deal)
          hermes-agent.nixosModules.default

          # 2. Hardware config (generated by nixos-generate-config on target)
          ./hardware-configuration.nix

          # 3. Hermes OS configuration
          ({ config, pkgs, lib, ... }:

          {
            # ─────────────────────────────────────────────────────────────
            # WHO AM I
            # ─────────────────────────────────────────────────────────────
            services.hermes-agent = {
              enable = true;

              user = deployment.agentUser;
              group = deployment.agentGroup;
              createUser = true;
              stateDir = deployment.stateDir;
              workingDirectory = deployment.workspaceDir;

              # OCI container mode — enables agent-managed operations including
              # apt/pip/npm installs, nixos-rebuild from inside the container,
              # and full self-modification. The NixOS store is bind-mounted
              # read-only; /var/lib/hermes and /etc/nixos are bind-mounted
              # read-write so the agent can modify its own environment.
              container.enable = true;
              container.backend = "docker";
              container.image = "ubuntu:24.04";

              # ─────────────────────────────────────────────────────────────
              # LLM PROVIDER
              # ─────────────────────────────────────────────────────────────
              settings = {
                provider = deployment.provider;
                model = deployment.model;
                toolsets = [ "all" ];
                terminal.backend = "local";
                compression.enabled = true;
                compression.threshold = 0.85;
                gateway.host = deployment.gatewayHost;
                gateway.port = deployment.gatewayPort;
                logging.level = "INFO";
              };

              # API keys via environment file (seeded from USB or set post-install)
              environmentFiles = [ deployment.secretsEnvFile ];

              environment = {
                HERMES_MANAGED = "true";
                HERMES_NODE_NAME = deployment.nodeName;
              };

              # ─────────────────────────────────────────────────────────────
              # SEED DOCUMENTS — placed in workspace on first deploy
              # ─────────────────────────────────────────────────────────────
              documents = {
                "SOUL.md" = ''
                  You are Hermes OS — a fully autonomous AI agent
                  running on your own hardware, your own infrastructure.

                  You own your environment completely. You can read and modify
                  every configuration file, every service, every tool.

                  Your purpose: work autonomously on any task, using your full
                  suite of skills, memory, and companions.

                  You are not a chatbot. You are an agent.
                '';

                "OPERATIONS.md" = ''
                  # Hermes OS — Operational Reference

                  ## System Paths
                  - State:  /var/lib/hermes/.hermes
                  - Config: /var/lib/hermes/.hermes/config.yaml
                  - Logs:   journalctl -u hermes-agent -f
                  - Memory:  /var/lib/hermes/.hermes/memories/
                  - Sessions: /var/lib/hermes/.hermes/sessions/
                  - Workspace: /var/lib/hermes/workspace/

                  ## Common Commands
                  - hermes status          # CLI status
                  - hermes-agent --version
                  - systemctl status hermes-agent
                  - journalctl -u hermes-agent -n 100 --no-pager

                  ## Self-Modification
                  - NixOS config: /etc/nixos/configuration.nix
                  - Rebuild:      sudo nixos-rebuild switch --flake /etc/nixos
                  - hermes config (YAML): /var/lib/hermes/.hermes/config.yaml
                  - Restart after config change: systemctl restart hermes-agent

                  ## Backup
                  - Wiki: cd /var/lib/hermes/wiki && git push
                  - Skills: cd /var/lib/hermes/skills && git push
                  - Dotfiles: /etc/nixos is a git repo

                  ## Update hermes-agent
                  - Update flake lock: cd /etc/nixos && sudo nix flake lock --update-input hermes-agent
                  - Rebuild: sudo nixos-rebuild switch --flake /etc/nixos
                  - Restart: systemctl restart hermes-agent
                '';
              };
            };

            # ─────────────────────────────────────────────────────────────
            # EXTRA PACKAGES available to the agent and interactive shell
            # ─────────────────────────────────────────────────────────────
            services.hermes-agent.extraPackages = import ./agent-extra-packages.nix { inherit pkgs; };

            # ─────────────────────────────────────────────────────────────
            # INTERACTIVE ADMIN USER
            # ─────────────────────────────────────────────────────────────
            users.users.${deployment.adminUser} = {
              isNormalUser = true;
              description = deployment.adminDescription;
              extraGroups = [ deployment.agentGroup "docker" "wheel" ];
              home = "/home/${deployment.adminUser}";
              createHome = true;
              shell = pkgs.bashInteractive;
            };

            # ─────────────────────────────────────────────────────────────
            # NETWORK
            # ─────────────────────────────────────────────────────────────
            networking.hostName = deployment.hostName;
            networking.useDHCP = lib.mkDefault true;

            services.openssh = {
              enable = true;
              settings = {
                PermitRootLogin = "no";
                PasswordAuthentication = false;
              };
            };

            # ─────────────────────────────────────────────────────────────
            # BOOT (Ventoy — no Grub)
            # ─────────────────────────────────────────────────────────────
            boot.loader.grub.enable = lib.mkForce false;
            boot.loader.generic-extlinux-compatible.enable = true;
            boot.initrd.availableKernelModules = [
              "ahci" "xhci_pci" "usb_storage" "nvme"
              "ext4" "vfat" "sr_mod" "sd_mod"
            ];

            # ─────────────────────────────────────────────────────────────
            # LOCALE / TIME
            # ─────────────────────────────────────────────────────────────
            time.timeZone = deployment.timeZone;
            i18n.defaultLocale = deployment.locale;

            # ─────────────────────────────────────────────────────────────
            # NIX
            # ─────────────────────────────────────────────────────────────
            nix.settings.experimental-features = [ "nix-command" "flakes" ];
            nix.settings.accept-flake-config = true;
            nix.gc.automatic = true;
            nix.gc.dates = "weekly";
            nix.gc.options = "--delete-older-than 30d";

            # ─────────────────────────────────────────────────────────────
            # SECURITY
            # ─────────────────────────────────────────────────────────────
            security.sudo.enable = true;
            boot.kernel.sysctl."kernel.randomize_va_space" = 2;

            # ─────────────────────────────────────────────────────────────
            # DOCUMENTATION (minimal — save space, docs in wiki)
            # ─────────────────────────────────────────────────────────────
            documentation.enable = false;
            documentation.man.enable = false;

            # ─────────────────────────────────────────────────────────────
            # VIRTUALISATION (Docker)
            # ─────────────────────────────────────────────────────────────
            virtualisation.docker.enable = true;

            # ─────────────────────────────────────────────────────────────
            # GATEWAY SECURITY — bind to localhost only.
            # Safe for LAN-isolated host. For reverse-proxy deployment,
            # bind to 127.0.0.1 and terminate TLS at the proxy.
            # ─────────────────────────────────────────────────────────────
            # Gateway host/port are configured in deployment-options.nix.
          })
        ];
      };
    };
}
