# hardware-configuration.nix — Generated by nixos-generate-config
# Review and adjust for your actual hardware before deploying
# Will be auto-generated on the target machine during install

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # ─── Boot ─────────────────────────────────────────────────────────────────
  boot.initrd.availableKernelModules = [
    "ahci" "xhci_pci" "usb_storage" "nvme" "ext4" "vfat"
    "sr_mod" "sd_mod" "rtsx_usb_sd"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # ─── Filesystems ─────────────────────────────────────────────────────────
  fileSystems = {
    "/" = {
      device = "/dev/nvme0n1p2";
      fsType = "ext4";
      options = [ "defaults" "noatime" "nodiratime" ];
    };

    "/boot/efi" = {
      device = "/dev/nvme0n1p1";
      fsType = "vfat";
      options = [ "defaults" ];
    };
  };

  swapDevices =
    let
      # Adjust UUID to your actual swap partition
      swap uuid = {
        device = "/dev/disk/by-uuid/${uuid}";
        randomizeEncryption = true;
      };
    in
    [
      # { device = "/dev/nvme0n1p3"; }
    ];

  # ─── Network ──────────────────────────────────────────────────────────────
  networking.useDHCP = lib.inNixShell;

  # ─── Power ───────────────────────────────────────────────────────────────
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # ─── Hardware ─────────────────────────────────────────────────────────────
  # CPU
  powerManagement.cpuFreq governors = lib.mkDefault [ "powersave" "performance" ];

  # GPU (uncomment and adjust for your hardware)
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  # };

  # Audio
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;

  # ─── Virtualization ──────────────────────────────────────────────────────
  virtualisation.docker.enable = true;
}
