# Target filesystem overrides generated by scripts/deploy-hermes.sh during live install.
# The checked-in default is intentionally empty so CI and local flake evaluation
# do not depend on deployment-specific UUIDs.
{ ... }:
{
}
